# Generated by Django 6.0.6 on 2026-06-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduTrack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='enrollment_number',
        ),
    ]
