# Generated by Django 6.0.6 on 2026-06-09 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_track', '0002_rename_student_id_student_enrollment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_track.student'),
        ),
        migrations.AlterField(
            model_name='module',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_track.course'),
        ),
        migrations.AlterField(
            model_name='result',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_track.module'),
        ),
        migrations.AlterField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_track.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolled_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_track.course'),
        ),
    ]
