# Generated by Django 6.0.6 on 2026-06-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_track', '0004_student_user_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
