# Generated by Django 6.0.6 on 2026-06-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_track', '0005_module_module_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
