# Generated by Django 6.0.6 on 2026-06-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_track', '0006_course_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
    ]
