# Generated by Django 6.0.6 on 2026-09-11 10:40
# Hand-written: adds AcademicYear / Semester / StudentEnrollment and rewires
# Module.courses -> Module.semester while preserving existing data.

import django.db.models.deletion
from django.db import migrations, models


def create_default_academic_year(apps, schema_editor):
    AcademicYear = apps.get_model("edu_track", "AcademicYear")
    if not AcademicYear.objects.exists():
        AcademicYear.objects.create(
            year_label="2025/2026",
            start_date="2025-09-01",
            end_date="2026-06-30",
        )


def link_modules_and_create_semesters(apps, schema_editor):
    AcademicYear = apps.get_model("edu_track", "AcademicYear")
    Course = apps.get_model("edu_track", "Course")
    Semester = apps.get_model("edu_track", "Semester")
    Module = apps.get_model("edu_track", "Module")

    academic_year = AcademicYear.objects.first()
    if academic_year is None:
        return

    for course in Course.objects.all():
        semester = Semester.objects.create(
            academic_year=academic_year,
            course=course,
            year_level=1,
            semester_number=1,
            name="Semester 1",
            start_date=academic_year.start_date,
            end_date=academic_year.end_date,
        )
        Module.objects.filter(courses_id=course.id).update(semester_id=semester.id)


def backfill_result_semesters(apps, schema_editor):
    Result = apps.get_model("edu_track", "Result")
    for result in Result.objects.filter(semester__isnull=True):
        if result.module_id is not None and result.module.semester_id is not None:
            result.semester_id = result.module.semester_id
            result.save(update_fields=["semester"])


class Migration(migrations.Migration):

    dependencies = [
        ("edu_track", "0008_result_unique_student_module_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year_label", models.CharField(max_length=50, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year_level", models.IntegerField(choices=[(1, "Year 1"), (2, "Year 2"), (3, "Year 3"), (4, "Year 4")], default=1)),
                ("semester_number", models.IntegerField(choices=[(1, "Semester 1"), (2, "Semester 2")], default=1)),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("academic_year", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="semesters", to="edu_track.academicyear")),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="semesters", to="edu_track.course")),
            ],
            options={
                "ordering": ["course", "year_level", "semester_number"],
            },
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enrollment_date", models.DateField()),
                ("status", models.CharField(choices=[("Enrolled", "Enrolled"), ("Completed", "Completed"), ("Dropped", "Dropped")], default="Enrolled", max_length=10)),
                ("academic_year", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to="edu_track.academicyear")),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to="edu_track.course")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to="edu_track.student")),
            ],
            options={
                "ordering": ["-academic_year__start_date", "student"],
            },
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(fields=("academic_year", "course", "year_level", "semester_number"), name="unique_semester_per_year_course"),
        ),
        migrations.AddConstraint(
            model_name="studentenrollment",
            constraint=models.UniqueConstraint(fields=("student", "course", "academic_year"), name="unique_student_course_academic_year"),
        ),
        migrations.RunPython(create_default_academic_year, migrations.RunPython.noop),
        migrations.AddField(
            model_name="module",
            name="semester",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="modules", to="edu_track.semester"),
            preserve_default=False,
        ),
        migrations.RunPython(link_modules_and_create_semesters, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="module",
            name="courses",
        ),
        migrations.AlterField(
            model_name="module",
            name="semester",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="modules", to="edu_track.semester"),
        ),
        migrations.AddField(
            model_name="result",
            name="semester",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="edu_track.semester"),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_result_semesters, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="result",
            name="unique_student_module_result",
        ),
        migrations.AlterField(
            model_name="result",
            name="semester",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="edu_track.semester"),
        ),
        migrations.AddConstraint(
            model_name="result",
            constraint=models.UniqueConstraint(fields=("student", "module", "semester"), name="unique_student_module_result"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="module",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="edu_track.module"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="semester",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="edu_track.semester"),
        ),
    ]