# Generated by Django 6.0.6 on 2026-09-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_track', '0009_semester_tracking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentenrollment',
            name='unique_student_course_academic_year',
        ),
        migrations.RemoveConstraint(
            model_name='result',
            name='unique_student_module_result',
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('student', 'module'), name='unique_student_module_result'),
        ),
        migrations.RemoveField(
            model_name='result',
            name='semester',
        ),
        migrations.DeleteModel(
            name='StudentEnrollment',
        ),
    ]
