# Generated by Django 6.0.6 on 2026-09-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_track', '0010_remove_studentenrollment_unique_student_course_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='year_level',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')], default=1),
        ),
    ]
